# Single dimension NumPy Array


In [2]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
type(n1)


numpy.ndarray

In [6]:
a=5

In [8]:
type(a)

int

In [10]:
a

5

In [16]:
number= int(input("Enter a positive integer"))
if number%2==0:
    print("It is even number")
else:
    print("It is odd number")

Enter a positive integer 3


It is odd number


# Multi-Dimensional NumPy Array


In [23]:
import numpy as np
n2=np.array([[10,20,30],[30,40,50],[60,70,80]])
n2

array([[10, 20, 30],
       [30, 40, 50],
       [60, 70, 80]])

# Initialize NumPy array with zeros

In [26]:
n3=np.zeros((2,3))
n3


array([[0., 0., 0.],
       [0., 0., 0.]])

# Initialize a array of a matrix with full then

n4=np.full((3,3),9)

In [33]:
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# Initialization of NumPy array within a range

In [42]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Initialization of the NumPy array with the skip numbers

In [47]:
n6=np.arange(1,10,2)
n6

array([1, 3, 5, 7, 9])

# Initialization Numpy array with the random numbers

In [50]:
n7=np.random.randint(100,1000,10)
n7

array([528, 229, 162, 574, 430, 138, 857, 461, 691, 364])

# Initialization of the array shape changes in a fraction of seconds

In [53]:
n8=np.array([[10,20,30],[10,80,90],[30,50,80]])
n8


array([[10, 20, 30],
       [10, 80, 90],
       [30, 50, 80]])

In [78]:
row1=np.arange(1,11)
row2=np.arange(11,20)
row3=np.arange(20,31)
row4=np.arange(31,40)
row5=np.arange(40,51)
row6=np.arange(51,60)
row7=np.arange(60,71)
row8=np.arange(71,80)
row9=np.arange(80,91)
row10=np.arange(91,100)
matrix=np.hstack((row1,row2,row3,row4,row5,row6,row7,row8,row9,row10))
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# joining NumPy Array

In [64]:
import numpy as np
a=np.array([10,20,30])
b=np.array([40,80,90])
np.vstack((a,b))

array([[10, 20, 30],
       [40, 80, 90]])

In [66]:
np.hstack((a,b))

array([10, 20, 30, 40, 80, 90])

In [68]:
np.hstack((a,b))

array([10, 20, 30, 40, 80, 90])

In [70]:
np.column_stack((a,b))

array([[10, 40],
       [20, 80],
       [30, 90]])

# NumPy intersection and differences 

In [80]:
x=np.array([10,20,30,40,50,60])
y=np.array([30,50,90,100,120,150])
np.intersect1d(x,y)

array([30, 50])

In [82]:
np.setdiff1d(x,y)

array([10, 20, 40, 60])

# Addition of NumPy Arrays

In [85]:
t=np.array([10,20])
s=np.array([30,40])
np.sum([t,s])

100

In [87]:
np.sum([t,s],axis=0)  #adds column

array([40, 60])

In [107]:
np.sum([t,s],axis=1)  #adds rows

array([30, 70])

In [91]:
p=np.array([10,20,30])
p+1

array([11, 21, 31])

In [93]:
p/2

array([ 5., 10., 15.])

In [95]:
p*2

array([20, 40, 60])

In [101]:
p*p

array([100, 400, 900])

In [103]:
p-2

array([ 8, 18, 28])

# NumPy as maths functions

In [110]:
nn=np.array([10,20,30,60])
np.mean(nn)

30.0

In [112]:
np.std(nn)

18.708286933869708

In [114]:
np.median(nn)

25.0

# saving and loading NumPy array

In [121]:
n11=np.array([10,20,30,40,50])
np.save('Spriha',n11)  #saving the numpy array
print (np.load('Spriha.npy'))  #loading the numpy array

[10 20 30 40 50]
